Use alpine and java 8 for docker images.
apache-spark-on-k8s/spark pull request #10
Opened 2017-01-11 22:19 UTC by mccheah

The first images were built more closely to what Spark has already done in their Mesos integration tests, but Alpine has a smaller image size and thus is quicker to pull and build with. Also use Java 8 instead of Java 7 as the base.

2017-01-11 22:20 UTC, mccheah commented on resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/driver/Dockerfile
> +RUN apk add --update vim
Mostly for debugging. Not sure what else we should add here, if anything.

2017-01-11 22:28 UTC, ash211 requested changes

2017-01-11 22:28 UTC, ash211 commented on resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/driver/Dockerfile
> +RUN apk add --update vim
There's no `vi` by default?  If so I'd want to keep this slimmer by not including `vim`

2017-01-11 22:28 UTC, ash211 commented on resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/executor/Dockerfile
>  # Remove unneeded /var/lib/apt/lists/* after install to reduce the
this comment no longer applicable since you removed that line

2017-01-11 22:28 UTC, ash211 commented on resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/driver/Dockerfile
>  # Remove unneeded /var/lib/apt/lists/* after install to reduce the
this comment no longer applicable since you removed that line

2017-01-11 22:35 UTC, mccheah commented on resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/driver/Dockerfile
> +RUN apk add --update vim
Ah good call, vi is there by default.

2017-01-11 23:47 UTC, mccheah commented
@ash211 anything else here?

2017-01-12 00:05 UTC, ash211 commented
Nope, LGTM!

2017-01-12 00:05 UTC, merged