Fix issue with DNS resolution
apache-spark-on-k8s/spark pull request #118
Opened 2017-02-15 08:01 UTC by foxish

Fixes https://github.com/apache-spark-on-k8s/spark/issues/112

2017-02-15 08:06 UTC, foxish commented on resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/kubernetes/integrationtest/minikube/Minikube.scala
> +    executeMinikube("docker-env", "--shell", "bash")
Also added this because I switched to a different shell and it was giving me odd errors because our string replacement relies on bash style output

2017-02-15 21:25 UTC, mccheah requested changes

2017-02-15 21:25 UTC, mccheah commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/scheduler/cluster/kubernetes/KubernetesClusterSchedulerBackend.scala
> +  private val kubernetesMaster = "https://kubernetes.default.svc"
Yup this works on my machine. Good find!

I think this string belongs in `constants.scala` and `KubernetesClientBuilder#buildFromWithinPod()` can just use that string directly. Remove the `kubernetesMaster` parameter from that method.

2017-02-16 00:44 UTC, mccheah approved these changes

2017-02-16 00:44 UTC, mccheah commented
Feel free to merge after the build passes. Thanks!

2017-02-16 00:51 UTC, ash211 approved these changes

2017-02-16 01:56 UTC, merged