Extract SSL configuration handling to a separate class
apache-spark-on-k8s/spark pull request #123
Opened 2017-02-16 01:41 UTC by mccheah

More or less a drag-and-drop of all the SSL related logic.

2017-02-16 01:44 UTC, mccheah commented
Soft dependency on #122 to fix merge conflicts as the refactors are done in a chain.

2017-02-23 22:53 UTC, mccheah commented
@ash211 @foxish @iyanuobidele this had a soft dependency on #122 which is now merged - can we look to review and merge this one now?

2017-02-23 23:06 UTC, iyanuobidele commented
LGTM

2017-02-23 23:57 UTC, foxish commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala
> +      kubernetesSslConfiguration: KubernetesSslConfiguration): KubernetesSparkRestApi = {
nit: can we just call it SSLConfiguration? The prefix `Kubernetes` seems to be everywhere.

2017-02-24 00:35 UTC, ash211 requested changes

2017-02-24 00:35 UTC, ash211 commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/KubernetesSslConfigurationProvider.scala
> +        case "container" => false
I think container isn't supposed to work anymore after this change https://github.com/apache-spark-on-k8s/spark/pull/107/files#diff-b5527f236b253e0d9f5db5164bdb43e9R79

2017-02-24 02:31 UTC, mccheah commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala
> +      kubernetesSslConfiguration: KubernetesSslConfiguration): KubernetesSparkRestApi = {
Done

2017-02-24 02:31 UTC, mccheah commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/KubernetesSslConfigurationProvider.scala
> +        case "container" => false
Done - changed to `local`

2017-02-24 02:35 UTC, ash211 approved these changes
LGTM let's merge when the build is green

2017-02-24 07:54 UTC, merged