V0.2 dev
apache-spark-on-k8s/spark pull request #341
Opened 2017-06-09 02:58 UTC by duyanghao

## What changes were proposed in this pull request?

Set driver and executor Label:spark-app-id = `--conf spark.kubernetes.driver.pod.name`.
The main reason for this is that we can search all pods for a spark application with the specified label(`spark-app-id`) value through par `spark.kubernetes.driver.pod.name`,which can be more easily combined with web server(if there is any),guess that use A specifies par `--conf spark.kubernetes.driver.pod.name=xxx`,then web server could get all pods information through k8s with label:`spark-app-id`=`xxx`,that is good anyway!!!
Refs [here](https://github.com/apache-spark-on-k8s/spark/issues/335).

## How was this patch tested?

Manual tests were successful.Example is as follows:

i submit with pars:
```
--conf spark.kubernetes.driver.pod.name=spark-pi-today-a
--conf spark.executor.cores=2
```
then driver pod name and labels will be:
```
kubectl describe pods/spark-pi-today-a
Name:		spark-pi-today-a
Namespace:	default
Node:		xxx
Start Time:	Tue, 06 Jun 2017 11:12:01 +0800
Labels:		spark-app-id=spark-pi-today-a
		spark-app-name=spark-pi
		spark-role=driver
Status:		Succeeded
```

executor #1 pod name and labels will be:
```
kubectl describe pods/spark-pi-today-a-exec-1
Name:		spark-pi-today-a-exec-1
Namespace:	default
Node:		xxx
Start Time:	Tue, 06 Jun 2017 11:12:33 +0800
Labels:		spark-app-id=spark-pi-today-a
		spark-exec-id=1
		spark-role=executor
Status:		Succeeded
```

executor #2 pod name and labels will be:
```
kubectl describe pods/spark-pi-today-a-exec-2
Name:		spark-pi-today-a-exec-2
Namespace:	default
Node:		xxx
Start Time:	Tue, 06 Jun 2017 11:12:33 +0800
Labels:		spark-app-id=spark-pi-today-a
		spark-exec-id=2
		spark-role=executor
Status:		Succeeded
```

2017-06-09 17:08 UTC, mccheah requested changes
I'm just marking this as unresolved until we have finished discussion on #335.

2017-06-09 17:17 UTC, mccheah commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/Client.scala
> +    val kubernetesAppId = sparkConf.getOption("spark.kubernetes.driver.pod.name")
I think this is out of date with branch-2.1-kubernetes - since #331 has merged, the semantics of these variables have changed.

2017-06-09 17:18 UTC, mccheah commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/Client.scala
> +    val driverCpuQuantity = new QuantityBuilder(false)
This is already included in #340

2017-08-21 22:54 UTC, ash211 commented
@duyanghao is this PR still active?  I'm not sure what's left since some of the pieces have been merged in through separate PRs.

If there are still changes that need to be made, please open a new PR against `branch-2.2-kubernetes` so we can get those merged in to this repo.

I figured that between fixing merge conflicts and changing the destination branch from 2.1 to 2.2 it's easier to start a new PR than continue working on this one.

Thanks again for helping make this project better!

2017-08-21 22:54 UTC, closed without merging