Support setting the driver pod launching timeout.
apache-spark-on-k8s/spark pull request #36
Opened 2017-01-22 14:54 UTC by lins05

## What changes were proposed in this pull request?

Support setting the driver pod launching timeout through `"spark.kubernetes.driverLaunchTimeout"`, and increase the default value from 30s to 60s. The current value of 30s is kind of short for pulling the image from public docker registry plus the container/JVM start time.

## How was this patch tested?

Manually test.

2017-01-24 00:09 UTC, foxish commented
I don't think `driverLaunchTimeout` adequately captures what the timeout really signifies. It is "local file upload timeout", and we should call it something like that IMO. WDYT @ash211 @mccheah

2017-01-24 00:13 UTC, mccheah commented
Driver launch timeout seems fine, I wouldn't want to make the config point too verbose. If we could come up with a config name that's concise and that captures the fact that we're waiting to upload data and start running the application, that's fine, but if anything we come up with is too verbose then this will suffice.

2017-01-24 00:27 UTC, foxish commented
I guess it isn't too bad a name. :) My concern was that except when uploading local jars, we should support a "fire and forget" type of launch mode, which would obviate the need for this timeout, and behave like the other schedulers in cluster mode. This is okay for now though.

2017-01-24 00:51 UTC, mccheah commented
Actually launch timeout is the correct term since the future's completion is contingent on both the pod watch indicating that the pod is in "ready" status and that the application has been submitted.

2017-01-24 01:07 UTC, foxish commented
Sounds good.
Maybe the future should be contingent on the pod entering the Pending/Ready/Running state in case we're not submitting anything from the local machine?

2017-01-24 01:11 UTC, mccheah commented
Hm, how is this different from the current world? Do you mean having two futures and blocking on each in turn - block on the first future to get the pod into ready status and block on the second future for finishing the submission to the driver server?

2017-01-24 01:50 UTC, erikerlandson commented
`fileStagingTimeout` ?

2017-01-25 06:24 UTC, lins05 commented
> Maybe the future should be contingent on the pod entering the Pending/Ready/Running state in case we're not submitting anything from the local machine?

For me the practical problem is it takes quite some time to pull the driver image from the public docker registry.  But it does sound like a good idea to output the detailed reason or phase of the pod when aborting the submit to k8s cluster, e.g. "the pod is running but the submit failed with error xyz", or "the pod has been pending for too long". Such details would help the user understand the reason of the failure and help locating/fixing the underlying problem.

What about merging this PR (maybe with another better name than `spark.kubernetes.driverLaunchTimeout`), and leave the more detailed error message described above for a future PR?

2017-01-25 08:15 UTC, foxish commented
LGTM. I'm ok with merging this for now. @mccheah, do you concur?

2017-01-25 08:24 UTC, ash211 requested changes

2017-01-25 08:24 UTC, ash211 commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala
> +  private val LAUNCH_TIMEOUT_SECONDS = 60
we should rename this to `DEFAULT_LAUNCH_TIMEOUT_SECONDS` now that it's configurable

2017-01-25 12:01 UTC, lins05 commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/Client.scala
> +  private val LAUNCH_TIMEOUT_SECONDS = 60
Make sense. I've updated it.

2017-01-25 19:05 UTC, ash211 approved these changes

2017-01-25 19:07 UTC, mccheah commented
Looks good to me

2017-01-25 19:07 UTC, merged