Fail submission if submitter-local files are provided without resourc…
apache-spark-on-k8s/spark pull request #447
Opened 2017-08-21 23:22 UTC by sahilprasad

…e staging server URI

Helpful validation to inhibit users from submitting local dependencies without specifying a URI for the RSS. Closes #339. 

## How was this patch tested?

Ran provided test suite and manually tested with local and non-local application dependency submissions.

2017-08-22 00:09 UTC, mccheah commented
This is not necessarily the case with https://github.com/apache-spark-on-k8s/spark/pull/437

2017-08-22 00:09 UTC, ash211 commented
Hi @sahilprasad , thanks for the contribution to this project!

Just earlier today we merged a PR that supports sending "small files" from the submitter to drivers/executors via k8s secrets, for a definition of small.  If the files aren't small enough and no RSS is specified, then it throws this exception: https://github.com/apache-spark-on-k8s/spark/pull/437/files#diff-5fd183129559d8c0a34135c347be647bR40

For jars there's no small jar vs large jar distinction, so any time there's a local jar there must be an RSS specified.

Were you looking at this primarily because of files or because of jars?

2017-08-22 01:05 UTC, sahilprasad commented
@ash211 I didn't realize that PR was there! I'm more concerned with jars here.
@mccheah Not necessarily as in small files submitted without an RSS specification will be sent through secrets, but not jars?

2017-08-22 01:07 UTC, mccheah commented
Yeah sorry, to clarify, this change is still valid for jars, but we need to be more careful with local files.

2017-08-22 01:13 UTC, sahilprasad commented
@mccheah Got it. If I were to change this just to accommodate jars, is there anything else in the way of jar-to-RSS validation that would be good to have?

2017-08-22 01:25 UTC, mccheah commented
jars probably don't need any special case. I think local files is actually already handled by the small files bootstrap given that we do a best effort to mount as a secret but when the files are too large we print an informative error message.

2017-08-22 01:33 UTC, sahilprasad commented
Right, is this change applicable, if modified, to just jars then?

2017-08-22 17:49 UTC, mccheah commented
I think so - should be able to write a unit and/or integration test that covers this.

2017-08-22 22:49 UTC, sahilprasad commented
@mccheah I can't get this test to pass when I build locally: https://github.com/apache-spark-on-k8s/spark/blob/branch-2.2-kubernetes/resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala#L72

Since the `SPARK_JARS` seq declared at the top of this class includes a submitter-local dependency (`file:///app/jars/jar2.txt`), that test fails with the validation error I am introducing with this PR. Since my test essentially constructs the orchestrator in the same way, and catches the thrown `IllegalArgumentException`, would that justify deleting this test?

2017-08-22 22:52 UTC, mccheah commented
This indicates to me that the validation is being added at the incorrect location, because the init container configuration steps orchestrator should always be being built with the arguments already having been validated. In other words, the orchestrator itself shouldn't be doing the validation, but some component above it.

2017-08-22 22:53 UTC, mccheah commented
Either that or the test should be patched to make it such that the orchestrator is created with "compatible" arguments - that is, if we're giving the orchestrator local files, it should also be given a resource staging server URI.

2017-08-23 00:12 UTC, sahilprasad commented
@mccheah Where would the validation take place if not `InitContainerConfigurationStepsOrchestrator`? `DriverConfigurationStepsOrchestrator`? The former class already has some validation around the RSS, so I figured I'd put my code there.

One way that I see to patch the test in question would be to include only the first element of `SPARK_JARS` (the jar prepended with `hdfs://`). This leads to a successful build. Do you suggest an alternative to this, or does my patch suffice?

2017-08-23 00:14 UTC, mccheah commented
The orchestrator can do the validation, but we should then change the test such that the arguments provided to the orchestrator line up with what the expectations are. We should be testing that

- When you use local jars, you must provide a resource staging server URI
- When you do not use local jars, it is not strictly necessary either way to provide this URI.

2017-08-23 21:31 UTC, sahilprasad commented
@mccheah can you review?

2017-08-23 21:33 UTC, mccheah requested changes

2017-08-23 21:33 UTC, mccheah commented on resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestrator.scala
> +    KubernetesFileUtils.getOnlySubmitterLocalFiles(sparkJars).nonEmpty match {
Don't match on true or false here - use the functional APIs like `map`, `filter`, `getOrElse`, etc.

2017-08-23 21:33 UTC, mccheah commented on resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala
> +    intercept[IllegalArgumentException] {
Can we inspect the correctness of the error message as well? We wouldn't want an `IllegalArgumentException` to come from some other part of the constructor.

2017-08-24 00:07 UTC, mccheah approved these changes

2017-08-24 00:07 UTC, mccheah commented
Ok to merge once the build passes.

2017-08-25 20:24 UTC, sahilprasad commented
@mccheah should I squash my commits, or is that done automatically?

2017-09-15 16:51 UTC, foxish commented
@mccheah this good to merge?

2017-09-15 16:56 UTC, ash211 commented on resource-managers/kubernetes/core/src/test/scala/org/apache/spark/deploy/kubernetes/submit/submitsteps/initcontainer/InitContainerConfigurationStepsOrchestratorSuite.scala
> +      SPARK_JARS.take(1),
this is a bit brittle in case SPARK_JARS changes in the future -- we should create a new `SPARK_JARS_REMOTE` that has only `hdfs://` path

2017-09-15 16:57 UTC, ash211 commented
Good to merge though, and Matt +1'd several weeks ago

2017-09-16 22:26 UTC, merged