Create README to better describe project purpose
apache-spark-on-k8s/spark pull request #50
Opened 2017-01-26 00:57 UTC by ash211

Fixes #35

2017-01-26 01:08 UTC, ash211 commented on README.md
> +- Red Hat
if I've left anyone off, or anyone wants this list changed, please let me know either here or in private

2017-01-26 19:25 UTC, mccheah requested changes
Small wording thing but overall seems ok.

2017-01-26 19:25 UTC, mccheah commented on README.md
> +Adding native integration for a new cluster manager is a large undertaking.  If poorly executed, it could introduce bugs into Spark when run on other cluster managers, cause release blockers slowing
"Any work this core in Spark" - what does this mean?

2017-01-27 05:14 UTC, foxish commented on README.md
> +- Code is primarily located in the [resource-managers/kubernetes](resource-managers/kubernetes) module
nit: We have multiple modules within that directory, but I think you don't mean module here in the maven sense.

2017-01-27 05:14 UTC, foxish commented on README.md
> +At the same time, an increasing number of people from varying companies and organizations desire to work together to natively run Spark on Kubernetes.  The group needs a code repository, communicatio
s/varying/various/?

2017-01-28 00:08 UTC, ash211 commented on README.md
> +- Code is primarily located in the [resource-managers/kubernetes](resource-managers/kubernetes) module
using folder instead

2017-01-28 00:08 UTC, ash211 commented on README.md
> +Adding native integration for a new cluster manager is a large undertaking.  If poorly executed, it could introduce bugs into Spark when run on other cluster managers, cause release blockers slowing
Changed to "Any work this deep inside Spark"

2017-01-28 00:08 UTC, ash211 commented on README.md
> +At the same time, an increasing number of people from varying companies and organizations desire to work together to natively run Spark on Kubernetes.  The group needs a code repository, communicatio
done

2017-01-28 00:08 UTC, ash211 commented
Responded to both your comments @foxish and @mccheah .  Anything else?

2017-01-28 00:18 UTC, foxish commented
LGTM

2017-01-28 00:20 UTC, mccheah commented
Looks great! I'm going to merge.

2017-01-28 00:20 UTC, mccheah approved these changes

2017-01-28 00:20 UTC, merged